# Generated by Django 4.2.14 on 2024-07-17 20:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Naciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wkt', models.CharField(max_length=254, null=True)),
                ('sistema_de', models.CharField(max_length=254, null=True)),
                ('punto_de_m', models.CharField(max_length=254, null=True)),
                ('n', models.CharField(max_length=254, null=True)),
                ('e', models.CharField(max_length=254, null=True)),
                ('nitrato', models.CharField(max_length=254, null=True)),
                ('distrito', models.CharField(max_length=254, null=True)),
                ('canton', models.CharField(max_length=254, null=True)),
                ('provincia', models.CharField(max_length=254, null=True)),
                ('r_cont_n', models.CharField(max_length=254, null=True)),
                ('c_canton', models.CharField(max_length=254, null=True)),
                ('point_x', models.CharField(max_length=254, null=True)),
                ('point_y', models.CharField(max_length=254, null=True)),
                ('id_n', models.IntegerField(null=True)),
                ('c_distrito', models.IntegerField(null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
